[package]
name = "game-life-rs"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies.gol-rs]
version = "0.1.0"
path = "../gol-rs"

[dependencies]
tui = "0.18"
crossterm = "0.23"